export const data = [
  {
    id: 1,
    name: "if looks could kill",
    artist: "Destroy Lonely",
    song_photo: "assets/cover-track/don toliver.jpg",
    song_duration: "3:45",
    track: "assets/music/Destroy_Lonely_-_if_looks_could_kill_76691308.mp3",
    explicit: true,
  },
  {
    id: 2,
    name: "Met Gala",
    artist: "Gunna",
    song_photo: "assets/cover-track/met gala Gunna.jpg",
    song_duration: "3:45",
    track: "assets/music/Gunna_-_MET_GALA_69667325 (1).mp3",
    explicit: true,
  },
  {
    id: 3,
    name: "Magnolia",
    artist: "Playboi Carty",
    song_photo: "assets/cover-track/magnolia playboi carty.webp",
    song_duration: "3:45",
    track: "assets/music/playboy carti - magnolia.mp3",
    explicit: true,
  },
  // {
  //   id: 3,
  //   name: "Flippin N Finessin",
  //   artist: "Kizary",
  //   song_photo: "assets/cover-track/flippin n finessin Kizary.jpg",
  //   song_duration: "3:45",
  //   track: "assets/music/FLIPPIN N FINESSIN.mp3",
  //   explicit: true,
  // },
  // {
  //   id: 4,
  //   name: "Skyscraper",
  //   artist: "Freindly thug 52, Markull",
  //   song_photo: "assets/cover-track/friendly rhug.jpg",
  //   song_duration: "3:45",
  //   track: "assets/music/FRIENDLY THUG 52 NGG, Markul - Skyscraper.mp3",
  //   explicit: true,
  // },
  // {
  //   id: 6,
  //   name: "Fake Id",
  //   artist: "Kizary, Icegergert",
  //   song_photo: "assets/cover-track/fake id.webp",
  //   song_duration: "3:45",
  //   track: "assets/music/Kizaru_feat_Icegergert_-_Fake_ID_79145305.mp3",
  //   explicit: true,
  // },
  
  {
    id: 4,
    name: "Is There Some Else?",
    artist: "The weeknd",
    song_photo: "assets/cover-track/is there some else.jpg",
    song_duration: "3:45",
    track: "assets/music/The_Weeknd_-_Is_There_Someone_Else_73626121.mp3",
    explicit: false,
  },
];
